function Hd = rechazobanda
%RECHAZOBANDA Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 27-Apr-2021 12:47:49

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N             = 110;      % Order
Fc1           = 195;      % First Cutoff Frequency
Fc2           = 600;      % Second Cutoff Frequency
flag          = 'scale';  % Sampling Flag
SidelobeAtten = 100;      % Window Parameter

% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'stop', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
